### PR TITLE
[bugfix] Fix redirect handling for 307 and 308 status codes

### LINKED ISSUE #32: Fix redirect behavior for 307/308 status codes
The way `RunWithContext` is set up inside `httpc`, it prevents some important features which are available via `NewRequestWithContext` from `net/http`:

> If body is of type *bytes.Buffer, *bytes.Reader, or *strings.Reader, the returned request's ContentLength is set to its exact value
> (instead of -1), GetBody is populated (so 307 and 308 redirects can replay the body), and Body is set to NoBody if the 
> ContentLength
> is 0.

This popped up testing github.com/els0r/goProbe trying to call `global-query` with `goQuery`, failing because the ingress in front of the global-query server redirected `/_query` to `/_query/`. `httpc`, or more specifically `net/http` wasn't following the request since the body isn't supplied to `NewRequestWithContext`.

### PR DESCRIPTION
**Pull request by els0r**
Set the `GetBody` function of a request explicitly when preparing the body. This makes sure that the client can follow redirects from 307 and 308 status codes without losing the original body.

Also, make sure that the `ContentLength` is set.

Closes #32

### CODE REVIEW

File: httpc.go [hunk 1]
```diff
@@ -298,14 +299,60 @@ func (r *Request) Run() error {
 	return r.RunWithContext(context.Background())
 }
 
+var (
+	errorEncodedRawBodyCollision = errors.New("cannot use both body encoding and raw body content")
+)
+
+func (r *Request) prepBody() (body io.ReadCloser, err error) {
+	// If requested, parse the requst body using the specified encoder
```
Comment (fako1024) [inline httpc.go:307]: Trivial nitpick: Please add an empty line before the comment to be consistent with the rest of the formatting.

**Review by fako1024 — APPROVED** [review]
Nice catch @els0r , thanks for taking a look at it: Aside from the trivial comment, could you maybe add a test covering this case (IIRC gock should also support redirect scenarios) to the suite?
In addition, I'd appreciate if @femaref could take a quick look at this PR as well (to make sure the proposed change doesn't have any side effects on existing stuff) and approve it.

**Review by femaref — APPROVED** [review]

**Comment by els0r** [comment]
Thanks for the approves. I'll need to do another round. Still getting redirect errors. Will increase test coverage.
